# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e0b7de933683e7d8d44cfbb02e7fcbccad2fbe120b86f22ed725887ba22de861ca821c0ef288084a36b0818b76af09e4a071d41ca9b5fa8f9ec7b5c97c8fa55

test:
  secret_key_base: 3bf1e33935d52d3ab411b312238e25163e1962b452ff4ccc248dfbc7d5f8cb1d295f551ef289ec654796c783b027a868976f2b3728f0f6fc0d48655fd314b7c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 905144e6b511e877d8901a3c579eac0eda3696d4b27c02fece3aa0cafb13c49832e8ff19698d17af8dcb2dbbd98ce3fe93d170128d6d60d4236beb79e107ab9b
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
